# Generated by Django 6.0.5 on 2026-05-27 08:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accent_color",
            field=models.CharField(
                default=accounts.models.generate_accent_color,
                editable=False,
                max_length=7,
            ),
        ),
    ]
