# Generated by Django 6.0.5 on 2026-06-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_profile_picture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="app_password",
        ),
    ]
