# Generated by Django 6.0.5 on 2026-06-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_userprofile_app_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="vault_password_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
