# Generated by Django 6.0.5 on 2026-05-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="device_type",
            field=models.TextField(
                blank=True,
                choices=[("pc", "PC"), ("mobile", "Mobile"), ("all", "All")],
                default="all",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="bookmarks.folder",
            ),
        ),
    ]
