# Generated by Django 6.0.5 on 2026-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0002_alter_bookmark_device_type_alter_bookmark_folder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="folder",
            new_name="folder_id",
        ),
    ]
