# Generated by Django 6.0.5 on 2026-05-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0003_rename_folder_bookmark_folder_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="folder_id",
            new_name="folder",
        ),
    ]
