# Generated by Django 6.0.5 on 2026-05-20 18:50

import bookmarks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0004_rename_folder_id_bookmark_folder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="folder",
            name="accent_color",
            field=models.CharField(
                default=bookmarks.models.generate_accent_color,
                editable=False,
                max_length=7,
            ),
        ),
    ]
