# Generated by Django 6.0.5 on 2026-06-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0008_tag_unique_user_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_vault",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="is_vault",
            field=models.BooleanField(default=False),
        ),
    ]
