# Generated by Django 6.0.5 on 2026-06-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0009_folder_is_vault_tag_is_vault"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="is_vault",
        ),
        migrations.AddField(
            model_name="bookmark",
            name="is_vault",
            field=models.BooleanField(default=False),
        ),
    ]
